application: robotscalgary
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: view/bootstrap

- url: /images
  static_dir: view/images

- url: /js
  static_dir: view/js
- url: /.*
  script: routes.application



libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest